### ISSUE TITLE
Should we be sending previousId explicitly on alias?

### ISSUE THREAD

**Issue by mattfeury** [segment-integrations/analytics-android-integration-mixpanel#11]
Referring to this code: https://github.com/segment-integrations/analytics-android-integration-mixpanel/blob/81d0d5633762d95c2e1e67e57bd0356951e61663/src/main/java/com/segment/analytics/android/integrations/mixpanel/MixpanelIntegration.java#L185

we've seen some instances where, due to network connectivity, the `identify` call is arriving to mixpanel *before* the `alias` call, which results in a broken user funnel. this shows up for us exclusively on android. [on the ios integration layer](https://github.com/segment-integrations/analytics-ios-integration-mixpanel/blob/3ca6048202941c8092e6f0f1cc971048a75560a9/Pod/Classes/SEGMixpanelIntegration.m#L199), the mixpanel previousId is being passed explicitly. seems like we should maintain this behavior on android. this way, even if the alias arrives after the identify, it will correctly connect the two ids.

thoughts?

**Comment by f2prateek** [comment]
Seems reasonable, 👍 from me (happy to accept a PR!)

**Comment by mattfeury** [comment]
thanks @f2prateek. just submitted one.
