### ISSUE TITLE
dyld: symbol not found: _objc_class_$_mixpanel 

### ISSUE THREAD

**Issue by f2prateek** [segment-integrations/analytics-android-integration-mixpanel#21]
Moved from https://github.com/segmentio/analytics-ios/issues/742

```
Hello, I'm getting this error while launch app.dyld: symbol not found: _objc_class_$_mixpanelI've added segment-mixpanel with pod:pod ‘Segment-Mixpanel’My project is written with swift.May you advice me something?
```

**Comment by f2prateek** [comment]
hey @bohachevskyy; I'm not sure what the issue is off the top of my head. I'd recommend contacting our support team https://segment.com/help/contact

cc @ladanazita for visibility

**Comment by bohachevskyy** [comment]
Thank you @f2prateek I've implemented Mixpanel manually, without segment.

**Comment by ladanazita** [comment]
@bohachevskyy Sorry for the delay here — looks like Prateek meant to open this up in the analytics-ios-integration-mixpanel repo :) 

Did you get a chance to submit an issue via our support form? We would love to help you out here, but need to understand a bit more context around your error.
