### ISSUE TITLE
Adding attributes to payload context in middleware doesn't work as mentioned in the documentation

### ISSUE THREAD

**Issue by okmanideep** [segment-integrations/analytics-android-integration-mixpanel#22]
[Middleware Documentation](https://segment.com/docs/sources/mobile/android/#middlewares) specifies to add attributes to your events by adding them to `context`.

But for mixpanel `context` seems to be only changing when `identify` is called. And the attributes added to `context` are not being reported to Mixpanel for `track` calls.

Took a look at the source and figured that `track` only sends `properties` to mixpanel and ignores the `context`.

Need to fix the discrepancy between the documentation and how mixpanel integration works.

**Comment by okmanideep** [comment]
@f2prateek Correct.

Just to add here - To add as properties, make sure the payload type is `track` and cast `BasePayload` as `TrackPayload`.

**Comment by okmanideep** [comment]
@f2prateek the docs are in `sources/mobile/android`. If `context` can't be modified for tracking events in mobile, consider changing the docs. Feel free to close this issue and open a corresponding one for docs.

**Comment by brennan** [comment]
Hey @okmanideep, I think our [spec doc here](https://segment.com/docs/spec/common/) and our [Mixpanel documentation](https://segment.com/docs/destinations/mixpanel/#collecting-contextual-properties) here may be helpful. Segment passes different contextual properties to downstream destinations based on what they support. In this case, Mixpanel only supports [limited contextual properties](https://segment.com/docs/destinations/mixpanel/#collecting-contextual-properties).

**Comment by okmanideep** [comment]
@brennan got it. Just that the sample in the [middleware documentation](https://segment.com/docs/sources/mobile/android/#middlewares) not working doesn't seem ideal.

**Comment by brennan** [comment]
@okmanideep I'll make a note that those docs may be confusing and pass it along to our support team. For integration-related questions, please feel free to ping our support team via the form [linked from the bottom of this page](https://segment.com/help). Thanks!
