### ISSUE TITLE
Alias issue

### ISSUE THREAD

**Issue by mirsaidoff** [segment-integrations/analytics-android-integration-mixpanel#23]
I track events and send them to Mixpanel (before sign up/log in). After sign up/login I am calling alias(newId) and identify(newId). Works fine! But after user logs out (gets new anonymous id, as I am calling reset() ) and logs in, those tracked events (between log out and log in) are recorded as separate user actions (orphaned), but after logging in the events are recorded correctly. How can I solve this?

**Comment by CarlosMecha** [comment]
Hi @mirsaidoff ! Could you run your workflow with the logger set to Debug? you will see when it's required to call `alias()` after the user logs out.
