### ISSUE TITLE
People properties list in Mixpanel doesn't get applied on Android.

### ISSUE THREAD

**Issue by bbeaird** [segment-integrations/analytics-android-integration-mixpanel#3]
The people properties list in Mixpanel doesn’t get applied on Android. The `properties to send as people properties` seen here - https://cloudup.com/cyc_PZ_16D5 - is mapped on ios seen here - https://github.com/segment-integrations/analytics-ios-integration-mixpanel/blob/95a3607a6c92bc2f524d52c26f8c44dd50a65424/Pod/Classes/SEGMixpanelIntegration.m#L86 - but not on android as seen here - https://github.com/segment-integrations/analytics-android-integration-mixpanel/blob/0266dca8c703932fbbb4676a5547b4e5d8730077/src/main/java/com/segment/analytics/android/integrations/mixpanel/MixpanelIntegration.java

Sperandio / Prateek said we should be able to get this into an upcoming sprint.

**Comment by hankim813** [comment]
@bbeaird can you add this to JIRA and then close the issue?

**Comment by bbeaird** [comment]
Added to jira.
